### PR TITLE
Added explicit module post-checkout hook execution

### PR DESCRIPTION
**Pull request by zokir**
To execute post-checkout hook

### CODE REVIEW

**Comment by novalis** [comment]
That is: why not just run the hook manually?

**Comment by bpeabody** [comment]
Yes, that is a good point too, @novalis . Further, I wonder if there are other operations we're performing to submodules besides this where hooks are not triggered. I suspect a more systematic approach is needed to do this "right". If this is just a hack to fix an internal situation for us, I'd rather patch it internally rather than doing something half-baked here, especially since that situation will be going away soon.

**Comment by novalis** [comment]
I think it's generally the right thing to do.  Maybe we also would want to run more hooks elsewhere (as we now do for other operations), but I don't think it's urgent to do those now.  It's sufficient to do them as we notice them.  This is the big one.

**Comment by bpeabody** [comment]
OK, I can live with that. Are we agreed that we will continue to call libgit2 checkout here, not shell out to git, but do invoke the hook if it exists?

I imagine there is some logic from invoking hooks in the meta-repo that we should be reusing?

**Comment by bpeabody** [comment]
We don't need this any more after https://github.com/twosigma/git-meta/pull/627

**Pull request closed without merging**
