### PR TITLE
Fix alternate ODB code

### PR DESCRIPTION
**Pull request by novalis**
Oops.  This code was in the wrong place.

### CODE REVIEW

**Comment by bpeabody** [comment]
Also, you're jhint check is failing.

**Comment by novalis** [comment]
Apparently messing with GIT_OBJECT_DIRECTORY is bad (even when I put it back after the test).  Doing GIT_ALTERNATE_OBJECT_DIRECTORIES instead.

**Comment by novalis** [comment]
Remaining test failure is known flakiness.

**Comment by novalis** [comment]
ping on this; it's blocking the hook from being used with a recent gitlab.

**Pull request merged**
