### PR TITLE
Adds logo image to README

### PR DESCRIPTION
**Pull request by petroseskinder**
Adds the below image to the README file. 

The image is located at `doc/git-meta-logo.png` [Preview](https://github.com/petroseskinder/git-meta) of what the final README will look like

image

reviewers: @bpeabody, @novalis, @jhedwardyang

### CODE REVIEW

**Comment by novalis** [comment]
Let's not use someone else's git logo?

**Comment by bpeabody** [comment]
Good point, @novalis. @petroseskinder, would you like to take a stab at making this a little more distinctive from the Git logo?

**Comment by petroseskinder** [comment]
@bpeabody that shouldn't be a problem. Is the issue with the logo on the left or the entire label?

**Comment by bpeabody** [comment]
Just the logo on the left, I believe.

**Comment by petroseskinder** [comment]
New Logo
git-meta logo

**Comment by novalis** [comment]
I like the first one.  The second has too much of the TS logo for my taste.

**Pull request merged**
