### PR TITLE
#403: make 'commit -i' mode not be comment lines

### PR DESCRIPTION
**Pull request by s-xiang**

### CODE REVIEW

**Comment by novalis** [comment]
Why is this the right thing to do?

**Comment by bpeabody** [comment]
@novalis : love to hear what you think on this.

current, e.g.:
```
# <*> enter meta-repo message above this line; delete this line to commit only submodules
```

proposed:

```
<*> enter meta-repo message above this line; delete this line to commit only submodules
```

**Comment by novalis** [comment]
I prefer with #.

**Comment by s-xiang** [comment]
Maybe we can make it more explicit for the user to know these lines are some behaviors that they can control? (change the line color and make the text more explicit?)

**Comment by bpeabody** [comment]
@s-xiang : we have no control over the coloring in the text editor; I believe `vim` has built in support for commit message files.

@novalis : I'm happy to put this issue on hold for now. I'll ask in our team chat real quick.

**Comment by bpeabody** [comment]
Going to put this on hold for now.

**Pull request closed without merging**
