### PR TITLE
stitching and destitching

### PR DESCRIPTION
**Pull request by bpeabody**
* performance improvements for stitching
* whitelist for unstitchable commits
* detstitch utility

### CODE REVIEW

**Comment by bpeabody** [comment]
@novalis -- I can't find the thread of the conversation (thanks, Github), but I cannot find any evidence (other than a vague comment in `git notes --help`) of either Git or libgit2 doing sharding, e.g.:

```bash
# libgit2
$ write-repos -o 'x=S:N refs/notes/foo 1=hi'
$ cd x
$ git checkout refs/notes/foo
Note: checking out 'refs/notes/foo'.

You are in 'detached HEAD' state. You can look around, make experimental
...
$ ls
d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
$ cat d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
hi
# Git
$ git notes add -m "hi" master
$ git checkout refs/notes/commits
Previous HEAD position was 50fcd21 Notes added by 'git_note_create' from libgit2
HEAD is now at 9c57bbf Notes added by 'git notes add'
$ ls
d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
$ cat d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
hi
```

**Comment by bpeabody** [comment]
To be sure Git wasn't being clever on the checkout (somehow removing the sharding from the notes), I looked at the tree associated with the commit:

```bash
$ git ls-tree 5a9b9489ff94683d76dde4e74ea7bd36919770c1
100644 blob 45b983be36b73c0788dc9cbcb76cbb80fc7bb057    d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
$ git show --pretty=%T refs/notes/commits
5a9b9489ff94683d76dde4e74ea7bd36919770c1

diff --git a/d70f4c5cd90b4c28df8e9f0616516b3af4c8b337 b/d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
new file mode 100644
index 0000000..45b983b
--- /dev/null
+++ b/d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
@@ -0,0 +1 @@
+hi
$ git ls-tree 5a9b9489ff94683d76dde4e74ea7bd36919770c1
100644 blob 45b983be36b73c0788dc9cbcb76cbb80fc7bb057    d70f4c5cd90b4c28df8e9f0616516b3af4c8b337
```

**Comment by novalis** [comment]
The sharding is adaptive, so you won't see it until you have a lot of notes.

**Comment by novalis** [comment]
You could always shard.  That would be simpler than having to do it adaptively.

**Comment by bpeabody** [comment]
OK, uploaded new version that writes bulk notes sharded and added support for reading sharded notes.

**Comment by bpeabody** [comment]
Uploaded new version fixing nit with variable scope and changing shard depth.

**Comment by bpeabody** [comment]
Fixed typos and changed exit code; landing.

**Pull request merged**
