### PR TITLE
Ignore sub remotes on push

### PR DESCRIPTION
**Pull request by bpeabody**
Note that I need to follow this up with a similar change to `pull`.

### CODE REVIEW

**Comment by jhedwardyang** [comment]
I'm not 100% sold on this idea for 2 main points:

1. Having 2 (or more) different servers for repositories seems like a very valid use case. I could want to tie together something on GitLab with something on Gitolite without moving a repository.
2. The behaviour of `git meta push` no longer matches `git push`.

**Comment by bpeabody** [comment]
I agree with the desirability of having multiple remotes (see the [wiki I just wrote](https://github.com/twosigma/git-meta/wiki/Subrepos-Without-Borders) for how this can work), but I don't think you want them to be configured at the submodule level. In fact change in this PR makes it easier to have multiple remotes. Imagine that you have a remote named `origin` and one named `gitlab`. If you ignore the submodule remotes, pushing to `origin` and `gitlab` works naturally: we grab the URL from the selected meta-repo remote and resolve our relative URL against it. If you don't do it this way, you have to make sure all the remotes are synchronized between the submodules and the meta-repo. Furthermore, I don't think it makes any sense to have `git meta push` send some commits to some repos and some to others based on configuration -- most likely such pushes would result in rejection on the back-end.

**Comment by bpeabody** [comment]
@novalis & @jhedwardyang: guys, can you come to an agreement on this today? It's blocking https://github.com/twosigma/git-meta/issues/111 and a related PR: https://github.com/twosigma/git-meta/pull/139.

**Comment by abliss** [comment]
What about ignoring submodule remotes when they are registered with a
relative URL, butty honoring them when absolute? Or offering a config
option to honor them ("never", "absolute", "always")?

**Comment by bpeabody** [comment]
We may learn more about how absolute URLs will be used (or that they just don't work with the overall strategy), but my instinct is that for the meta-repo to make sense, synthetic-meta-refs need to go to the meta-repo-configured location. If we were pushing user-named tags or refs, it would be a different story, but I don't see a valid use-case for users to interfere with the destination of synthetic-meta-refs.

At this moment, I don't want to add configurability until we have a valid use case -- it's just another potential source of problems.

**Comment by abliss** [comment]
SGTM

**Comment by bpeabody** [comment]
@novalis What say ye? Can this go in?

**Comment by novalis** [comment]
Sure.

**Pull request merged**
